language: c
sudo: required
service: docker
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script:
  - bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=mpris
  matrix:
    - DISTRO="debian-9-ocaml-4.02"
    - DISTRO="debian-9-ocaml-4.03"
    - DISTRO="debian-9-ocaml-4.04"
    - DISTRO="debian-9-ocaml-4.05"
